version: '2'

services:
    agile-core:
      image: agileiot/agile-core-$ARCH
      volumes:
        - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
      environment:
        - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
      ports:
        - 8080:8080/tcp
      restart: always
      privileged: true
      command: bash -c "scripts/start.sh DeviceManager & scripts/start.sh ProtocolManager & scripts/start.sh http"

    agile-ble:
      image: agileiot/agile-core-$ARCH
      volumes:
        - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
      environment:
        - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
      restart: always
      privileged: true
      network_mode: "host"
      command: bash -c "mkdir -p /var/run/dbus && dbus-daemon --system && /usr/local/libexec/bluetooth/bluetoothd -E & sleep 10 && scripts/start.sh BLE"

    agile-ui:
      image: agileiot/agile-ui-armv7l
      depends_on:
        - agile-core
      environment:
        - AGILE_CLIENT_PORT=$AGILE_CLIENT_PORT
      ports:
        - $AGILE_CLIENT_PORT:$AGILE_CLIENT_PORT
      restart: always

    agile-osjs:
      image: agileiot/agile-osjs-armv7l
      depends_on:
        - agile-core
      ports:
        - 8000:8000/tcp
      restart: always

    agile-nodered:
      image: agileiot/agile-nodered-armv7l
      hostname: agile-nodered
      volumes:
        - $HOME/.agile/nodered:/root/.node-red
      ports:
        - 1880:1880/tcp
      links:
        - agile-core:agile
      restart: always

    agile-influxdb:
      image: $IMAGE_INFLUXDB
      volumes:
       - $HOME/.agile/influxdb:/var/lib/influxdb
      ports:
        - 8083:8083/tcp
        - 8086:8086/tcp
      restart: always

    agile-grafana:
      image: $IMAGE_GRAFANA
      volumes:
       - $HOME/.agile/grafana:/var/lib/grafana
      ports:
        - 3000:3000/tcp
      restart: always

    agile-zb:
      image: agileiot/agile-zb-armv7l
      volumes:
        - /dev/ttyUSB0:/dev/ttyUSB0 \
        - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
      environment:
        - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
      command: python3 dbus_server/dbus_server.py
      privileged: true

    agile-zb-lamp:
      image: agileiot/agile-zb-armv7l
      depends_on:
        - agile-zb
      volumes:
        - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
      environment:
        - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
      command: python3 ge_link_bulb/ge_link_bulb_device.py
      privileged: true
